name: Publish to JSR
on:
  push:
    tags:
      - 'v*' # This will trigger the workflow when you push a tag starting with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed for JSR authentication
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Publish to JSR
        run: deno publish
        env:
          JSR_TOKEN: ${{ secrets.JSR_TOKEN }}
